# -*- coding: utf-8 -*-
"""EMA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qO2kNdRnq84YVZNy1nkUChE_dpW3l5d
"""

pip install yfinance

import yfinance as yf
import pandas as pd

t = list = ["A","AA","AAL","AAP","AAPL","ABBV","ABT","ADBE","ADI","ADM","ADP","ADS","ADSK","AEE","AES",
"AFL","AIG","AIV","AIZ","AJG","AKAM","ALB","ALGN","ALK","ALL","ALXN","AMAT","AMD","AME","AMG","AMGN",
"AMP","AMT","AMZN","AN","ANSS","ANTM","APA","APD","APH","ARE","ARNC","ATVI","AVB",
"AVGO","AVY","AXP","AYI","AZO",
"BA","BAC","BAX","BBBY","BBY","BDX","BEN","BHF",
"BIIB","BK","BKNG","BLK","BLL","BMY","BRK-B","BSX","BWA","BXP",
"C","CAG","CAH","CAT","CBOE",
"CBRE","CCI","CERN","CF","CFG","CHD","CHK","CHRW","CHTR","CI","CINF","CL","CLF","CLX",
"CMA","CMCSA","CME","CMG","CMI","CMS","CNC","CNP","COF","COG","COO","COP","COST","COTY","CPB",
"CRM","CSCO","CTAS","CTSH","CTXS","CVS","CVX",
"DAL","DE","DFS","DG","DGX","DHI","DHR","DIS",
"DISCA","DISCK","DLR","DLTR","DNB","DRI","DTE","DVA","DVN","DXC",
"EA","EBAY","ECL","ED",
"EFX","EIX","EL","EMN","EMR","EOG","EQIX","EQT","ES","ESS"
"F","FAST","FB","FBHS","FCX","FDX","FE","FFIV","FIS","FISV","FITB",
"FL","FLIR","FLR","FLS","FMC","FOX","FOXA","FSLR","FTR","FTV","GD","GE","GGP","GILD","GIS","GLW",
"GM","GOOG","GOOGL","GPC","GPN","GPS","GS","GT","GWW","HAL","HAS","HBAN","HBI","HCA","HCP","HD",
"HES","HIG","HLT","HOG","HOLX","HON","HP","HPE","HPQ","HRB","HRL","HRS","HSIC","HST","HSY","HUM",
"IBM","ICE","IDXX","IFF","ILMN","INCY","INTC","INTU","IP","IPG","IRM","ISRG","IT","ITW","JBHT",
"JEC","JNJ","JNPR","JPM","JWN","K","KEY","KHC","KIM","KLAC","KMB","KMI","KMX","KO","KR","KSU","L",
"LB","LEG","LEN","LEN-B","LH","LKQ","LLL","LLY","LM","LMT","LNT","LOW","LRCX","LUK","LUV","M","MA",
"MAA","MAC","MAR","MAS","MAT","MCD","MCHP","MCK","MCO","MDLZ","MET","MHK","MKC","MLM","MMC","MMM",
"MNST","MO","MON","MOS","MPC","MRK","MRO","MS","MSFT","MSI","MTB","MTD","MU","MUR","NAVI","NBL","NDAQ",
"NEE","NEM","NFLX","NFX","NKE","NOC","NOV","NRG","NSC","NTAP","NTRS","NUE","NVDA","NWL","NWS","NWSA",
"O","OI","OKE","OMC","ORCL","ORLY","OXY","PANW","PBCT","PBI","PCAR","PCG","PDCO","PEG","PEP","PFE","PFG",
"PG","PGR","PH","PHM","PKI","PLD","PM","PNC","PPG","PPL","PRU","PSA","PSX","PVH","PWR","PX","PXD","PYPL","QCOM",
"QRVO","R","REG","REGN","RF","RHI","RHT","RJF","RL","ROK","ROP","ROST","RRC","RSG","RTN","SBUX","SCG","SCHW",
"SEE","SHW","SJM","SLG","SNA","SNPS","SO","SOHU","SPG","SPGI","SPLK","SQ","SRCL","SPOT","SRE","STT","STZ","SWK",
"SWKS","SWN","SYF","SYK","SYMC","SYY","T","TAP","TDC","TDG","TGNA","TGT","TIF","TJX","TMK","TMO","TPR","TRIP",
"TROW","TRV","TSCO","TSLA","TSN","TSS","TWTR","TWX","TXN","TXT","UA","UAA","UAL","UDR","UHS","ULTA","UNH","UNM",
"UNP","UPS","URBN","URI","USB","UTX","V","VAR","VFC","VIAB","VLO","VMC","VNO","VRSK","VRSN","VRTX","VTR","VZ","WAT",
"WBA","WDC","WEC","WELL","WFC","WHR","WM","WMB","WMT","WRK","WU","WY","WYN","WYNN","XEC","XEL","XLNX","XOM","XRAY","XRX","XYL","YUM","ZBH","ZION","ZTS"]

k = list = []
i = 0
sum = 0
s = 0
print("Какой период?")
n = int(input())
d = n
alpha = 2/(1+n)
p = 0
pw = 0
while i < 422:
  if i == 78:
    i = i + 1
  p = 0
  sum = 0
  s = 1
  a = yf.download(t[i], start="2020-01-01", end="2021-07-17")
  #now = yf.download(t[i], start="2021-07-16", end="2021-07-17")
  close = a["Close"]
  nn = len(close)
  while s <= n:
    a = yf.download(t[i], start="2020-01-01", end="2021-07-17")
    close = a["Close"]
    sum = sum + close[s]
    s = s + 1
  sum = sum/n
  ema = sum
  while n <= nn:
    ema = alpha*close[n-1] + (1-alpha)*ema
    n = n + 1
  n = d
  now = yf.download(t[i], start="2021-07-16", end="2021-07-17")
  close = a["Close"]
  v = close[len(close)-1]
  pnow = now["Close"]
  pw = pnow[0]
  p = (pw-ema)/pw
  if p <= 0.05 and p >= -0.015:
    k[len(k):] = [t[i]]
  print(t[i], ema, pnow[0],p, k)
  i = i + 1 
  
print(k)



now = yf.download("MSFT", start="2021-07-16", end="2021-07-17")
now

print(i)

print(i)









