# -*- coding: utf-8 -*-
"""snp500.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3M7foZb3V6A4R4am46jYFO_LuG4l_E8
"""

!pip install yfinance
!pip install arrow

import yfinance as yf
import pandas as pd
import arrow
t = list = ["A","AA","AAL","AAP","AAPL","ABBV","ABT","ADBE","ADI","ADM","ADP","ADS","ADSK","AEE","AES",
"AFL","AIG","AIV","AIZ","AJG","AKAM","ALB","ALGN","ALK","ALL","ALXN","AMAT","AMD","AME","AMG","AMGN",
"AMP","AMT","AMZN","AN","ANSS","ANTM","APA","APD","APH","ARE","ARNC","ATVI","AVB",
"AVGO","AVY","AXP","AYI","AZO",
"BA","BAC","BAX","BBBY","BBY","BDX","BEN","BHF",
"BIIB","BK","BKNG","BLK","BLL","BMY","BRK-B","BSX","BWA","BXP",
"C","CAG","CAH","CAT","CBOE",
"CBRE","CCI","CERN","CF","CFG","CHD","CHK","CHRW","CHTR","CI","CINF","CL","CLF","CLX",
"CMA","CMCSA","CME","CMG","CMI","CMS","CNC","CNP","COF","COG","COO","COP","COST","COTY","CPB",
"CRM","CSCO","CTAS","CTSH","CTXS","CVS","CVX",
"DAL","DE","DFS","DG","DGX","DHI","DHR","DIS",
"DISCA","DISCK","DLR","DLTR","DNB","DRI","DTE","DVA","DVN","DXC",
"EA","EBAY","ECL","ED",
"EFX","EIX","EL","EMN","EMR","EOG","EQIX","EQT","ES",
"F","FAST","FB","FBHS","FCX","FDX","FE","FFIV","FIS","FISV","FITB",
"FL","FLR","FLS","FMC","FOX","FOXA","FSLR","FTV","GD","GE","GILD","GIS","GLW",
"GM","GOOG","GOOGL","GPC","GPN","GPS","GS","GT","GWW","HAL","HAS","HBAN","HBI","HCA","HD",
"HES","HIG","HLT","HOG","HOLX","HON","HP","HPE","HPQ","HRB","HRL","HSIC","HST","HSY","HUM",
"IBM","ICE","IDXX","IFF","ILMN","INCY","INTC","INTU","IP","IPG","IRM","ISRG","IT","ITW","JBHT","JNJ","JNPR","JPM","JWN","K","KEY","KHC","KIM","KLAC","KMB","KMI","KMX","KO","KR","KSU","L",
"LB","LEG","LEN","LEN-B","LH","LKQ","LLY","LMT","LNT","LOW","LRCX","LUV","M","MA",
"MAA","MAC","MAR","MAS","MAT","MCD","MCHP","MCK","MCO","MDLZ","MET","MHK","MKC","MLM","MMC","MMM",
"MNST","MO","MOS","MPC","MRK","MRO","MS","MSFT","MSI","MTB","MTD","MU","MUR","NAVI","NDAQ",
"NEE","NEM","NFLX","NKE","NOC","NOV","NRG","NSC","NTAP","NTRS","NUE","NVDA","NWL","NWS","NWSA",
"O","OI","OKE","OMC","ORCL","ORLY","OXY","PANW","PBCT","PBI","PCAR","PCG","PDCO","PEG","PEP","PFE","PFG",
"PG","PGR","PH","PHM","PKI","PLD","PM","PNC","PPG","PPL","PRU","PSA","PSX","PVH","PWR","PXD","PYPL","QCOM",
"QRVO","R","REG","REGN","RF","RHI","RJF","RL","ROK","ROP","ROST","RRC","RSG","SBUX","SCHW",
"SEE","SHW","SJM","SLG","SNA","SNPS","SO","SOHU","SPG","SPGI","SPLK","SQ","SRCL","SRE","STT","STZ","SWK",
"SWKS","SWN","SYF","SYK","SYY","T","TAP","TDC","TDG","TGNA","TGT","TJX","TMO","TPR","TRIP",
"TROW","TRV","TSCO","TSLA","TSN","TWTR","TXN","TXT","UA","UAA","UAL","UDR","UHS","ULTA","UNH","UNM",
"UNP","UPS","URBN","URI","USB","V", "VFC","VLO","VMC","VNO","VRSK","VRSN","VRTX","VTR","VZ","WAT",
"WBA","WDC","WEC","WELL","WFC","WHR","WM","WMB","WMT","WRK","WU","WY","WYNN","XEC","XEL","XLNX","XOM","XRAY","XRX","XYL","YUM","ZBH","ZION","ZTS"]
k = list = []
d = arrow.now().format('YYYY-MM-DD')
i = 137

while i <=421:
  a = yf.download(t[i], start="2021-07-01", end=d)
  snp = yf.download(t[i], start="2020-03-23", end="2020-03-24") #Данные по s&p500 (Менять тут)
  closeA = a["Close"]
  closeSNP = snp["Close"]
  k1 = (closeA[len(a)-2]-closeSNP[0])/(closeSNP[0])
  if k1 <= 0.05 and k1 >= -0.05: #И тут, дельта от уровня большого падения s&p500
    k[len(k):] = [t[i]]
    print(t[i])
    print(k)
    i = i + 1
  else:
    print(t[i])
    print(k)
    i = i + 1









print(i)





















print(i)



def f(x):
  return x + 2
x = int(input())
print(f(x)) 2020-03-23

print(i)











